// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.DAL;

#nullable disable

namespace TestTask.DAL.Migrations
{
    [DbContext(typeof(TestTaskDbContext))]
    [Migration("20231223170150_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8"),
                            Title = "Admin"
                        },
                        new
                        {
                            Id = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70"),
                            Title = "User"
                        },
                        new
                        {
                            Id = new Guid("a97fb48b-c9c4-46c1-a8f7-3e7df678010d"),
                            Title = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("20253c25-6a04-457c-bab8-bf3c124820b1"),
                            Title = "Support"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b4898ce-0b12-493e-9a5d-4c5685ee7070"),
                            Age = 25,
                            Email = "penis@gmail.com",
                            FullName = "Mike Vazovskiy",
                            PasswordHash = "$2a$11$dP.CERPy/dTWDRvwVZlGIOy9EVTyD.XmnbcMcUp4NF8MbG4QokOvu"
                        },
                        new
                        {
                            Id = new Guid("218705ea-7161-4485-8bfb-978abc280ac6"),
                            Age = 16,
                            Email = "penis.vonyaet@gmail.com",
                            FullName = "Mike Popchinskiy",
                            PasswordHash = "$2a$11$DucitYFpc7fvJT7KwGXXj.tXA8n5VvZM/7UQUqAgWqbm1G4GKAgi6"
                        },
                        new
                        {
                            Id = new Guid("fba5aaee-f86d-47e4-a1b1-dc19be451356"),
                            Age = 19,
                            Email = "kurwa.vonyaet@gmail.com",
                            FullName = "Mike Kurwa",
                            PasswordHash = "$2a$11$VVJ7tprqDiqytykEnGEZ8u1alJUG4nfERAHpFA743pOykTct4CL0m"
                        },
                        new
                        {
                            Id = new Guid("b594fb48-c68d-4edf-a542-eeb9331f24c4"),
                            Age = 28,
                            Email = "jopka@gmail.com",
                            FullName = "Sally Vazovskiy",
                            PasswordHash = "$2a$11$lFT.q313wcB8ZJK0fya3D.Va1bJGkQupr9jrZlk.7Z/5Y6Xy.gC.G"
                        },
                        new
                        {
                            Id = new Guid("f370d916-2219-4cc2-acd8-8eddff93f509"),
                            Age = 34,
                            Email = "govno@gmail.com",
                            FullName = "Ivan Vazovskiy",
                            PasswordHash = "$2a$11$jbYCelEnNnwzS4SI60llCeNAE4XVmO3PN9HtBZe4S.j687uYmYZgC"
                        },
                        new
                        {
                            Id = new Guid("33ae8884-ac1a-450e-b4fc-2b7f9c881c57"),
                            Age = 30,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            PasswordHash = "$2a$11$6rOm1UZomBv0S4j5KPVqbeKQnOa/8vMIPKicg/eQJn5gGtekFyHbC"
                        },
                        new
                        {
                            Id = new Guid("15088f35-6457-4f2f-a5ca-e52db5c57f34"),
                            Age = 28,
                            Email = "john.doe.jr@example.com",
                            FullName = "John Doe Jr.",
                            PasswordHash = "$2a$11$ivjCOanPT2eN5bz.KfbNMuFvzFuZBAPv9Yso1k1uPNQv7F4MXx.gO"
                        },
                        new
                        {
                            Id = new Guid("67300aa7-f59e-4dc3-9d0d-24d5c999fec2"),
                            Age = 55,
                            Email = "john.doe.sr@example.com",
                            FullName = "John Doe Sr.",
                            PasswordHash = "$2a$11$xivxWkkAztAyB8AdS5E8NOOFXjueQXdeYnMmwb8KxpIqeeL5gAd/q"
                        },
                        new
                        {
                            Id = new Guid("82e6497b-8773-436b-a65b-46e4efab62ec"),
                            Age = 22,
                            Email = "alice.johnson@example.com",
                            FullName = "Alice Johnson",
                            PasswordHash = "$2a$11$x/ZeLtIbjMzoZn4IlT0AYeBOvP59MPZa95BvROjFgsFhs4rwS/4qG"
                        },
                        new
                        {
                            Id = new Guid("f0e4bf66-6b73-4b7e-9eb7-4a09def821d0"),
                            Age = 25,
                            Email = "alice.johnson.ii@example.com",
                            FullName = "Alice Johnson II",
                            PasswordHash = "$2a$11$irB6ifkUMhA0BdIWnl4Lb.EqAR2jnn8v8CmI7kNmRKQdwfZ0.MHpa"
                        },
                        new
                        {
                            Id = new Guid("d26e3b9e-11e5-4d28-84ec-102f1f4158e5"),
                            Age = 32,
                            Email = "alice.johnson.iii@example.com",
                            FullName = "Alice Johnson III",
                            PasswordHash = "$2a$11$mOer3S3gL4c.ZigoH4T07e5/urJlWpj4DO43wWriYxf8Rp8VIFtW2"
                        },
                        new
                        {
                            Id = new Guid("7c9a7c01-92a1-4aba-a792-eb99454a7999"),
                            Age = 45,
                            Email = "bob.smith@example.com",
                            FullName = "Bob Smith",
                            PasswordHash = "$2a$11$bMivIJrhs/xs/gl.jNbnJuTIOe1TlxVh5Ir9Ast6f6PMnYQ7Gi/bi"
                        },
                        new
                        {
                            Id = new Guid("f3594cfc-2959-4197-a0d3-64dfd4f1f26c"),
                            Age = 30,
                            Email = "bob.smith.jr@example.com",
                            FullName = "Bob Smith Jr.",
                            PasswordHash = "$2a$11$QrW0ew1qrjfbsosr5qMTqeGqkOEE6.olWnQTLAtQkURlFCQRBDXTO"
                        },
                        new
                        {
                            Id = new Guid("d5c12da2-dcc5-4aa8-8b80-068ff4073d9e"),
                            Age = 35,
                            Email = "bob.smith.iii@example.com",
                            FullName = "Bob Smith III",
                            PasswordHash = "$2a$11$EshUVTkqnbNLKN0aMKRaF.zkcW78QfUTJW3AYnEw1FWcBNvTIqZwa"
                        },
                        new
                        {
                            Id = new Guid("4a71158c-da2e-45ad-a551-102c9bf7f138"),
                            Age = 28,
                            Email = "emily.white@example.com",
                            FullName = "Emily White",
                            PasswordHash = "$2a$11$TxtRIB2XCnC5YzHnLgA1feeX2FbJTgDqWcKMxM.EioOwSOAps64Pu"
                        },
                        new
                        {
                            Id = new Guid("cbf6657f-1bb7-43ec-8740-5e66615a9dc8"),
                            Age = 32,
                            Email = "emily.white.ii@example.com",
                            FullName = "Emily White II",
                            PasswordHash = "$2a$11$4eVQeWLLA2mtkePUDPemrefgHYNxJbg4qg8EM8o7Ojempm3B6ulWq"
                        },
                        new
                        {
                            Id = new Guid("12a3c182-9a87-43ba-9f4e-547c71bda8fb"),
                            Age = 27,
                            Email = "emily.white.iii@example.com",
                            FullName = "Emily White III",
                            PasswordHash = "$2a$11$TigpovzV0HRcD3eUbwu4i.yBNo2X56MwhIJTAcQbgXFGCeeldpCSm"
                        },
                        new
                        {
                            Id = new Guid("feaaa763-f3f6-4a68-ba40-a2ea556d8e44"),
                            Age = 35,
                            Email = "daniel.brown@example.com",
                            FullName = "Daniel Brown",
                            PasswordHash = "$2a$11$edyzWH1aUyUDF5J8ZepF5OlOTDJP8x0RxnoOKIXKcnfIIha.PO8Oq"
                        },
                        new
                        {
                            Id = new Guid("ad2ce995-fee4-44f2-9255-067576d960c9"),
                            Age = 29,
                            Email = "daniel.brown.jr@example.com",
                            FullName = "Daniel Brown Jr.",
                            PasswordHash = "$2a$11$twY5Cj3I3ZHoNFzPMeWLC.CWnZ82f8/68kX6wCkB4kyS.KScY9KWu"
                        },
                        new
                        {
                            Id = new Guid("18218134-b959-4f8b-8835-46d1d1ebb823"),
                            Age = 33,
                            Email = "daniel.brown.iii@example.com",
                            FullName = "Daniel Brown III",
                            PasswordHash = "$2a$11$RQkEznGFpb5zsJU9PHc9FupSWkBD5v9zDTybkUrZBDPEExgIc5Y0S"
                        },
                        new
                        {
                            Id = new Guid("d291cc71-ed41-4dac-87b7-41054c7af4e6"),
                            Age = 26,
                            Email = "sophia.black@example.com",
                            FullName = "Sophia Black",
                            PasswordHash = "$2a$11$an2t0GagZV1FF10MdaVvXe6Y1U8BbuXXELEe6gXZ6ph/q1iIZVP7u"
                        },
                        new
                        {
                            Id = new Guid("af7a643f-aef1-4dcf-938e-785ea8cb3cfe"),
                            Age = 31,
                            Email = "jack.miller@example.com",
                            FullName = "Jack Miller",
                            PasswordHash = "$2a$11$oVR5hXPuY1W4cjmjWVz6Qu07gRmPKlY7MvpsxOpxqJZjoTbf2artu"
                        },
                        new
                        {
                            Id = new Guid("47130bc1-1da1-4ff5-bb2e-14b445288c7f"),
                            Age = 29,
                            Email = "emma.green@example.com",
                            FullName = "Emma Green",
                            PasswordHash = "$2a$11$TUh9ZJX26d7jZ.OLqUWUuuhUSP4Anc7HWutQV6/vJ5WFvtRP6VACy"
                        },
                        new
                        {
                            Id = new Guid("9541b57e-38c0-4443-99b4-9d482e76342d"),
                            Age = 40,
                            Email = "michael.grey@example.com",
                            FullName = "Michael Grey",
                            PasswordHash = "$2a$11$NzyMYQRlgYsrHflWruN2xOFIi47VeP63X1nZeoUdHdalgFfM9H3/u"
                        },
                        new
                        {
                            Id = new Guid("c9e02761-3237-4fff-8000-c849f4eb1efe"),
                            Age = 24,
                            Email = "olivia.red@example.com",
                            FullName = "Olivia Red",
                            PasswordHash = "$2a$11$1LDi/OAEdYzf.bSpB0kwy.3UMG8Qzv06uxlP5sYp2w2Ldhi9SYvze"
                        },
                        new
                        {
                            Id = new Guid("cf59211b-8078-42fc-b61c-6333c78a6e04"),
                            Age = 33,
                            Email = "william.yellow@example.com",
                            FullName = "William Yellow",
                            PasswordHash = "$2a$11$U8p0Ixym6uEKlOnQ72PeV.74UEq1WINpsUWzeUaAVIr6YWmUgGzqK"
                        },
                        new
                        {
                            Id = new Guid("ed6c2ac1-d517-44a4-9b4e-248ce11b0ec7"),
                            Age = 27,
                            Email = "ava.purple@example.com",
                            FullName = "Ava Purple",
                            PasswordHash = "$2a$11$gI9.skIi52qzhJWNjDMQVuwT6RFH7wBRH8f0VzDgfez7IPTRPANXy"
                        },
                        new
                        {
                            Id = new Guid("a7225293-3ab5-4d7f-9b9d-37e0dd9be8ff"),
                            Age = 14,
                            Email = "james.orange@example.com",
                            FullName = "James Orange",
                            PasswordHash = "$2a$11$gAhK0NXWxOBT.Q/mnvw9L.Dngv7aEwSHLAuaXLi8F7zskswg1zrgK"
                        },
                        new
                        {
                            Id = new Guid("d2070028-8290-4fe0-aff2-96872a3a2fa6"),
                            Age = 25,
                            Email = "mia.pink@example.com",
                            FullName = "Mia Pink",
                            PasswordHash = "$2a$11$2xZt1JnVPL4BciLGQWmNGOgKGXOUGbPTZ8D5h6lXqm87b6JmhU5MK"
                        },
                        new
                        {
                            Id = new Guid("0aee01ff-fd94-4180-9f37-ad841653e254"),
                            Age = 18,
                            Email = "ethan.silver@example.com",
                            FullName = "Ethan Silver",
                            PasswordHash = "$2a$11$lRTmOLZAAnNvjAVVtPgdTuOlYE0TwHdgGvtVurhomUQGKdF1aBiOO"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7b4898ce-0b12-493e-9a5d-4c5685ee7070"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("7b4898ce-0b12-493e-9a5d-4c5685ee7070"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("7b4898ce-0b12-493e-9a5d-4c5685ee7070"),
                            RoleId = new Guid("a97fb48b-c9c4-46c1-a8f7-3e7df678010d")
                        },
                        new
                        {
                            UserId = new Guid("218705ea-7161-4485-8bfb-978abc280ac6"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("218705ea-7161-4485-8bfb-978abc280ac6"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("218705ea-7161-4485-8bfb-978abc280ac6"),
                            RoleId = new Guid("a97fb48b-c9c4-46c1-a8f7-3e7df678010d")
                        },
                        new
                        {
                            UserId = new Guid("fba5aaee-f86d-47e4-a1b1-dc19be451356"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("fba5aaee-f86d-47e4-a1b1-dc19be451356"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("fba5aaee-f86d-47e4-a1b1-dc19be451356"),
                            RoleId = new Guid("a97fb48b-c9c4-46c1-a8f7-3e7df678010d")
                        },
                        new
                        {
                            UserId = new Guid("b594fb48-c68d-4edf-a542-eeb9331f24c4"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("b594fb48-c68d-4edf-a542-eeb9331f24c4"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("f370d916-2219-4cc2-acd8-8eddff93f509"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("f370d916-2219-4cc2-acd8-8eddff93f509"),
                            RoleId = new Guid("20253c25-6a04-457c-bab8-bf3c124820b1")
                        },
                        new
                        {
                            UserId = new Guid("33ae8884-ac1a-450e-b4fc-2b7f9c881c57"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("15088f35-6457-4f2f-a5ca-e52db5c57f34"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("67300aa7-f59e-4dc3-9d0d-24d5c999fec2"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("82e6497b-8773-436b-a65b-46e4efab62ec"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("f0e4bf66-6b73-4b7e-9eb7-4a09def821d0"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("d26e3b9e-11e5-4d28-84ec-102f1f4158e5"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("7c9a7c01-92a1-4aba-a792-eb99454a7999"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("7c9a7c01-92a1-4aba-a792-eb99454a7999"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("f3594cfc-2959-4197-a0d3-64dfd4f1f26c"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("f3594cfc-2959-4197-a0d3-64dfd4f1f26c"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("d5c12da2-dcc5-4aa8-8b80-068ff4073d9e"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("d5c12da2-dcc5-4aa8-8b80-068ff4073d9e"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("4a71158c-da2e-45ad-a551-102c9bf7f138"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("cbf6657f-1bb7-43ec-8740-5e66615a9dc8"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("12a3c182-9a87-43ba-9f4e-547c71bda8fb"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("feaaa763-f3f6-4a68-ba40-a2ea556d8e44"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("feaaa763-f3f6-4a68-ba40-a2ea556d8e44"),
                            RoleId = new Guid("20253c25-6a04-457c-bab8-bf3c124820b1")
                        },
                        new
                        {
                            UserId = new Guid("ad2ce995-fee4-44f2-9255-067576d960c9"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("ad2ce995-fee4-44f2-9255-067576d960c9"),
                            RoleId = new Guid("20253c25-6a04-457c-bab8-bf3c124820b1")
                        },
                        new
                        {
                            UserId = new Guid("18218134-b959-4f8b-8835-46d1d1ebb823"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("18218134-b959-4f8b-8835-46d1d1ebb823"),
                            RoleId = new Guid("20253c25-6a04-457c-bab8-bf3c124820b1")
                        },
                        new
                        {
                            UserId = new Guid("d291cc71-ed41-4dac-87b7-41054c7af4e6"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("af7a643f-aef1-4dcf-938e-785ea8cb3cfe"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("47130bc1-1da1-4ff5-bb2e-14b445288c7f"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("47130bc1-1da1-4ff5-bb2e-14b445288c7f"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("9541b57e-38c0-4443-99b4-9d482e76342d"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("c9e02761-3237-4fff-8000-c849f4eb1efe"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("cf59211b-8078-42fc-b61c-6333c78a6e04"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("ed6c2ac1-d517-44a4-9b4e-248ce11b0ec7"),
                            RoleId = new Guid("d92227c9-43b5-413b-976f-aeed7c374ae8")
                        },
                        new
                        {
                            UserId = new Guid("ed6c2ac1-d517-44a4-9b4e-248ce11b0ec7"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("a7225293-3ab5-4d7f-9b9d-37e0dd9be8ff"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("d2070028-8290-4fe0-aff2-96872a3a2fa6"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        },
                        new
                        {
                            UserId = new Guid("d2070028-8290-4fe0-aff2-96872a3a2fa6"),
                            RoleId = new Guid("20253c25-6a04-457c-bab8-bf3c124820b1")
                        },
                        new
                        {
                            UserId = new Guid("0aee01ff-fd94-4180-9f37-ad841653e254"),
                            RoleId = new Guid("edbfdba1-54d9-4c9e-9f26-f85037648d70")
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTask.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
